### ISSUE TITLE
How to modify acs view to allow configuration per company (multi-tenant)?

### ISSUE THREAD

**Issue by wise-ubuntu** [loadimpact/django-saml2-auth#169]
I would need to add `path("acs/<int:customer_id>/", views.acs, name="acs")` and then in acs view get configuration based on customer (company) ID.

```
@csrf_exempt
@exception_handler
def acs(request: HttpRequest, customer_id: int):
    company = Company.objects.get(pk=customer_id)
    saml2_auth_settings = {
        'METADATA_AUTO_CONF_URL': company.sso_metadata_url,
        'ASSERTION_URL': company.sso_assertion_url,
        'ENTITY_ID': company.sso_entity_id
        ...
    }
```
but in other methods, for example, in saml.py file, configuration is get from `settings.SAML2_AUTH` and I do not know how to adjust it. Any recommendations?

**Comment by mostafa** [comment]
Hey @wise-ubuntu,

Use the [`GET_USER_ID_FROM_SAML_RESPONSE` trigger](https://github.com/grafana/django-saml2-auth/blob/6b3d05460f24e3b213f560ede0ce4ede975ca66f/django_saml2_auth/saml.py#L164-L167) to narrow your search scope for the metadata URLs. If the `user_id` is returned from the trigger function, it'll be passed to the [`get_metadata`](https://github.com/grafana/django-saml2-auth/blob/6b3d05460f24e3b213f560ede0ce4ede975ca66f/django_saml2_auth/saml.py#LL169C20-L169C20) function, which subsequently passes it to the `GET_METADATA_AUTO_CONF_URLS` trigger function, where you can find which company the user belongs to and then load that specific metadata autoconf URL.

**⚠️ Warning**
Use this with extra caution, as the returned `SAMLResponse` is not verified at the stage when the `GET_USER_ID_FROM_SAML_RESPONSE` function is triggered. That is, you are using the raw unverified SAML response.

**Comment by jeremylivingston** [comment]
@mostafa I am running into a similar situation, but only for users who have not been created and are logging in for the first time through their IDP.

Details of my scenario:

1. Account administrator sets up an SSO configuration for their app. We save the metadata for this configuration.
2. A user attempts to sign in via the IDP who has not yet signed in before and therefore has no account
3. The `GET_USER_ID_FROM_SAML_RESPONSE` cannot find a user since they do not exist yet
4. We're unable to pass the user_id to `GET_METADATA_AUTO_CONF_URLS` to pull their specific metadata file

One option would be to return a different ID (the team ID instead of the user ID) from the `GET_USER_ID_FROM_SAML_RESPONSE` call, then use that downstream, but it seems like this could have unintended side effects. Is there a recommended approach for how to handle this situation?
